import { describe, it, expect } from 'vitest';
import { createHmac } from 'node:crypto';
import {
  verifyChatwootSignature,
  computeChatwootSignature,
  readSignatureHeaders,
  DEFAULT_TOLERANCE_SECONDS,
} from './chatwoot-webhook-signature';

// Fixed, obviously-synthetic test key. The real bot secret lives only in the
// Foundation environment as CHATWOOT_BOT_SIGNING_SECRET and must never appear
// in the repository.
const TEST_KEY = 'unit-test-key-0000';
const BODY = '{"event":"message_created","id":42,"conversation":{"inbox_id":46}}';
const TS = '1785000000';
const NOW = Number(TS) * 1000;

function sign(secret: string, ts: string, body: string): string {
  return `sha256=${createHmac('sha256', secret).update(`${ts}.${body}`).digest('hex')}`;
}

describe('computeChatwootSignature', () => {
  // Reproduces lib/webhooks/trigger.rb exactly:
  //   "sha256=" + OpenSSL::HMAC.hexdigest('SHA256', secret, "#{ts}.#{body}")
  it('matches the Ruby construction', () => {
    expect(computeChatwootSignature(TEST_KEY, TS, BODY)).toBe(sign(TEST_KEY, TS, BODY));
  });

  // Golden vector generated by the RUNNING Chatwoot 4.16.1 image, not by this
  // implementation, so a refactor cannot silently drift away from Chatwoot:
  //   docker exec <rails> ruby -e 'require "openssl";
  //     puts OpenSSL::HMAC.hexdigest("SHA256", "unit-test-key-0000",
  //       "1785000000.{\"event\":\"message_created\",...}")'
  it('matches a signature produced by the live Chatwoot Ruby', () => {
    expect(computeChatwootSignature(TEST_KEY, TS, BODY)).toBe(
      'sha256=06399b79ebad49c10bbe3725b2a1e158f90e980151b78f7049dce88d0dc6dbf6',
    );
  });

  it('produces a sha256= prefixed 64-char lowercase hex digest', () => {
    expect(computeChatwootSignature(TEST_KEY, TS, BODY)).toMatch(/^sha256=[0-9a-f]{64}$/);
  });

  it('signs timestamp and body jointly, so they cannot be swapped', () => {
    // If the separator were ignored, these two would collide.
    const a = computeChatwootSignature(TEST_KEY, '12', '3.body');
    const b = computeChatwootSignature(TEST_KEY, '123', '.body');
    expect(a).not.toBe(b);
  });
});

describe('verifyChatwootSignature', () => {
  const base = { rawBody: BODY, secret: TEST_KEY, timestamp: TS, nowMs: NOW };

  it('accepts a genuine delivery', () => {
    const r = verifyChatwootSignature({ ...base, signature: sign(TEST_KEY, TS, BODY) });
    expect(r.ok).toBe(true);
  });

  it('rejects a body tampered with in flight', () => {
    const r = verifyChatwootSignature({
      ...base,
      rawBody: BODY.replace('"inbox_id":46', '"inbox_id":3'),
      signature: sign(TEST_KEY, TS, BODY),
    });
    expect(r).toEqual({ ok: false, reason: 'signature-mismatch' });
  });

  it('rejects a signature made with the wrong secret', () => {
    const r = verifyChatwootSignature({ ...base, signature: sign('wrong-secret', TS, BODY) });
    expect(r).toEqual({ ok: false, reason: 'signature-mismatch' });
  });

  it('fails closed when no secret is configured', () => {
    const r = verifyChatwootSignature({ ...base, secret: '', signature: sign(TEST_KEY, TS, BODY) });
    expect(r).toEqual({ ok: false, reason: 'no-secret-configured' });
  });

  it.each([
    ['missing signature', { signature: null }, 'missing-signature'],
    ['missing timestamp', { signature: sign(TEST_KEY, TS, BODY), timestamp: null }, 'missing-timestamp'],
    ['unprefixed signature', { signature: 'a'.repeat(64) }, 'malformed-signature'],
    ['short signature', { signature: 'sha256=abc' }, 'malformed-signature'],
    ['uppercase hex', { signature: `sha256=${'A'.repeat(64)}` }, 'malformed-signature'],
    ['non-numeric timestamp', { signature: sign(TEST_KEY, TS, BODY), timestamp: 'now' }, 'malformed-timestamp'],
  ] as const)('rejects %s', (_label, override, reason) => {
    const defaults = {
      ...base,
      signature: sign(TEST_KEY, TS, BODY) as string | null,
      timestamp: TS as string | null,
    };
    const r = verifyChatwootSignature({ ...defaults, ...override });
    expect(r).toEqual({ ok: false, reason });
  });

  describe('replay protection', () => {
    it('rejects a delivery older than the tolerance window', () => {
      const old = String(Number(TS) - DEFAULT_TOLERANCE_SECONDS - 1);
      const r = verifyChatwootSignature({
        ...base,
        timestamp: old,
        signature: sign(TEST_KEY, old, BODY),
      });
      expect(r).toEqual({ ok: false, reason: 'stale-timestamp' });
    });

    it('accepts a delivery inside the window', () => {
      const recent = String(Number(TS) - (DEFAULT_TOLERANCE_SECONDS - 10));
      const r = verifyChatwootSignature({
        ...base,
        timestamp: recent,
        signature: sign(TEST_KEY, recent, BODY),
      });
      expect(r.ok).toBe(true);
    });

    // A far-future timestamp is still a validly-signed request; without an
    // upper bound it would remain replayable indefinitely.
    it('rejects a far-future timestamp, not just an old one', () => {
      const future = String(Number(TS) + DEFAULT_TOLERANCE_SECONDS + 1);
      const r = verifyChatwootSignature({
        ...base,
        timestamp: future,
        signature: sign(TEST_KEY, future, BODY),
      });
      expect(r).toEqual({ ok: false, reason: 'stale-timestamp' });
    });

    it('honours a disabled window when tolerance is 0', () => {
      const ancient = '1000000000';
      const r = verifyChatwootSignature({
        ...base,
        timestamp: ancient,
        signature: sign(TEST_KEY, ancient, BODY),
        toleranceSeconds: 0,
      });
      expect(r.ok).toBe(true);
    });
  });

  it('handles an empty body without throwing', () => {
    const r = verifyChatwootSignature({ ...base, rawBody: '', signature: sign(TEST_KEY, TS, '') });
    expect(r.ok).toBe(true);
  });

  it('is byte-exact: reserialised JSON does not verify', () => {
    // The guard against parsing before verifying — JSON.stringify(JSON.parse(x))
    // reorders nothing here but drops the original spacing.
    const spaced = '{"event": "message_created"}';
    const compact = JSON.stringify(JSON.parse(spaced));
    expect(compact).not.toBe(spaced);
    const r = verifyChatwootSignature({
      ...base,
      rawBody: compact,
      signature: sign(TEST_KEY, TS, spaced),
    });
    expect(r.ok).toBe(false);
  });
});

describe('readSignatureHeaders', () => {
  it('reads the three headers case-insensitively', () => {
    const h = new Headers({
      'X-Chatwoot-Signature': 'sha256=abc',
      'X-Chatwoot-Timestamp': '123',
      'X-Chatwoot-Delivery': 'del-1',
    });
    expect(readSignatureHeaders(h)).toEqual({
      signature: 'sha256=abc',
      timestamp: '123',
      deliveryId: 'del-1',
    });
  });

  it('returns nulls when the headers are absent', () => {
    expect(readSignatureHeaders(new Headers())).toEqual({
      signature: null,
      timestamp: null,
      deliveryId: null,
    });
  });
});
