/**
 * Claim-guard — output filter enforcing the approved Claim Register + hard-never
 * list for the EMA/Isola sales-concierge agents ("Iris" in the Lane 1 dispatch).
 *
 * Why this is a post-generation filter, not a prompt edit: these agents run on
 * brain_provider='clawith', where the reply text is generated by an external
 * system (Clawith/Paperclip) that this repo has no credentials for and does not
 * control — tryIsolaBridge()/tryClawithLegacy() in brain-provider.ts never
 * forward the `system` prompt to it. This is the only reachable enforcement
 * point for any provider's output, called from generateReply()'s single
 * chokepoint in lib/brain-provider.ts.
 *
 * Scope: enforcement (block + deflect) applies ONLY to SALES_TENANT_IDS below.
 * A platform-wide audit-only detector for all clawith tenants is an explicit
 * future follow-on — applying this tenant's price allow-list to other tenants
 * would incorrectly block their own real prices.
 */

export const SALES_TENANT_IDS: ReadonlySet<string> = new Set([
  'ema_sales_tenant',
  '43b006e4-33e0-42a8-bec7-4422ba290d79',
]);

// Ratified once-off/setup + monthly figures (EC$) from the approved Claim
// Register. No other EC$ figure may appear in a sales-tenant reply.
// 375 = SBL setup, billed as two EC$375 installments (before work +
// on acceptance) — both installments share this one figure.
const RATIFIED_EC_AMOUNTS = new Set([750, 249, 250, 99, 149, 375]);
// Ratified per-minute voice rate — sourced from the same env var Magnus/Lite
// billing already uses, so this can't drift from the live billing rate.
const RATIFIED_PER_MIN_RATE = Number(process.env.LITE_DOMINICA_RATE_EC_PER_MIN ?? '0.27');

export interface GuardResult {
  text: string;
  blocked: boolean;
  /** Rule id, for audit logging only — never included in the customer-facing text. */
  rule?: string;
}

// Exported so brain-provider.ts can reuse the exact same claim-safe text on
// the fail-closed guard-error path — one source of truth for what the
// customer sees when the guard can't vouch for the raw reply, whether that's
// a rule hit or an unexpected error evaluating the rules.
export const DEFLECTION =
  "I don't have a confirmed answer for that — let me get you accurate details from our team. I'll flag this conversation for a person to follow up.";

// Hard-never deny-list — heuristic regexes, first pass. Expect tuning as the
// regression suite and live traffic surface false positives/negatives.
//
// requiresPositiveClaim: for a handful of rules, a bare keyword match also
// fires on an honest negative disclaimer ("we don't offer a complex IVR"),
// which fails safe (deflect + escalate, never a fabrication) but generates a
// false escalation. Those rules are checked with isNegatedClaim() below so
// only an affirmative claim blocks. Left false (the default) for the rest of
// the deny-list, which is first-pass and tuned from the audit log instead.
const HARD_NEVERS: { id: string; pattern: RegExp; requiresPositiveClaim?: boolean }[] = [
  // voice_ai — the sales agent (in ANY grammatical person) claiming an AI answers/handles
  // phone or VOICE calls. Covers the literal "voice AI", third-person "our AI answers your
  // calls", AND the first-person framing EMA actually used on 2026-07-18 ("I answer the call",
  // "I also answer phone calls"). The object is pinned to phone/voice CALLS so approved claims
  // pass: "answers your WhatsApp" (T1) has no call object, and "you make/receive calls on the
  // softphone" (T5) has a CUSTOMER subject, not an AI subject. Not requiresPositiveClaim -> an
  // honest "we don't offer voice AI" over-blocks to a human, which fails safe.
  { id: 'voice_ai', pattern: /\bvoice[\s-]?AI\b|\b(?:AI|assistant|receptionist|bot|I|we)(?:'ll| will| can| could| also| do| now| even| still| that| which| who)*\s+(?:answers?|answer|picks?(?:\s+up)?|pick(?:\s+up)?|takes?|handles?)\b(?:\s+[\w'-]+){0,6}?\s+(?:phones?(?!\s+(?:plan|bill|number|settings|contract|charger|case|screen|app|model|company|carrier|provider))|voice[\s-]?calls?|voice[\s-]?line|calls?)\b/i },
  // ai_voice_channel — the WhatsApp AI ALSO running the voice/call channel: "same AI on
  // WhatsApp and voice", "same AI, both channels" (the exact cross-channel fabrication in the
  // 2026-07-18 Tests 1 & 4), plus an AI/assistant/first-person subject tied to "both channels"
  // or a "WhatsApp and voice" pairing.
  { id: 'ai_voice_channel', pattern: /\bsame\s+AI\b[^.?!]{0,45}\b(?:voice|calls?|phone|both\s+channels)\b|\b(?:AI|assistant|receptionist|bot|I)\b[^.?!]{0,30}\b(?:both\s+channels|voice\s+and\s+whatsapp|whatsapp\s+and\s+voice)\b/i },
  // ai_places_call — the assistant offering to autonomously PLACE/MAKE an outbound call, or to
  // call the customer ("I can place an outbound call", "I'll call you back"). Subject-anchored to
  // the AI/assistant ("I"/"our AI"/"let me") so approved customer-side calling ("you can make and
  // receive calls from a softphone", T5 — a "you" subject) is never caught.
  { id: 'ai_places_call', pattern: /\b(?:I|let me|our (?:AI|assistant|bot))(?:'ll| will| can| could| also)*\s+(?:place|places|placed|make|makes|dial|dials|initiate|initiates|put through|ring|rings)\s+(?:you |them |him |her )?(?:an?|the|your|a|one|that)?\s*(?:outbound|out-?going|automated|quick|phone|direct)?\s*calls?\b|\b(?:I|our (?:AI|assistant|bot))(?:'ll| will| can| could)*\s+(?:call|calls|ring|rings|dial|dials)\s+(?:you|them|him|her|your\s+customers?|the\s+customers?|customers?|back)\b/i },
  { id: 'unlimited_autonomy', pattern: /\bunlimited autonomy\b|\bfully autonomous\b|\bno human (oversight|involvement|needed)\b/i },
  { id: 'guaranteed_accuracy', pattern: /\bguarantee[sd]?\b[^.?!]{0,40}\b(sales|accuracy|results|conversion)s?\b/i, requiresPositiveClaim: true },
  { id: 'missed_call_recovery', pattern: /\bmissed[\s-]call recovery\b|\brecovers?\s+(every|all)\s+missed calls?\b/i },
  { id: 'complex_ivr', pattern: /\bIVR\b|\bmulti-?level (phone )?menu\b/i, requiresPositiveClaim: true },
  { id: 'instant_self_service', pattern: /\binstant self-?service\b|\b14-?day free\b|\bself-?serve sign-?up\b/i },
  { id: 'automated_refunds', pattern: /\bautomat(ed|ic) refunds?\b/i, requiresPositiveClaim: true },
  { id: 'every_intl_route', pattern: /\bevery international (route|destination)\b|\ball countries\b/i, requiresPositiveClaim: true },
  { id: 'autonomous_finance', pattern: /\bautonomous(ly)?\s+(move|transfer|charge)s?\b|\bAI\s+(can|will)\s+(move|transfer)\s+money\b/i },
  // Order-independent: catches both "guaranteed migration of every WhatsApp
  // number" and "we migrate every WhatsApp number, guaranteed."
  { id: 'guaranteed_migration', pattern: /(?=[\s\S]*\bguarantee[sd]?\b)(?=[\s\S]*\bmigrat(e|ion|ing)\b)(?=[\s\S]*\b(every|all)\s+(your\s+)?WhatsApp numbers?\b)/i },
];

const NEGATION_WORDS = /\b(don't|doesn't|do not|does not|won't|will not|can't|cannot|can not|isn't|is not|aren't|are not|never|unable to)\b/i;

// True if `text` reads as an honest disclaimer rather than a claim at the
// match starting at `matchIndex` — i.e. a negation word appears earlier in
// the same sentence (scanning back to the previous sentence boundary).
function isNegatedClaim(text: string, matchIndex: number): boolean {
  let sentenceStart = 0;
  for (let i = matchIndex - 1; i >= 0; i--) {
    if (text[i] === '.' || text[i] === '?' || text[i] === '!') {
      sentenceStart = i + 1;
      break;
    }
  }
  return NEGATION_WORDS.test(text.slice(sentenceStart, matchIndex));
}

// For requiresPositiveClaim rules: true only if some occurrence of `pattern`
// in `text` is NOT a negated disclaimer. Non-flagged rules keep the simpler
// any-match-blocks behavior via pattern.test() in guardReply below.
function hasPositiveClaim(text: string, pattern: RegExp): boolean {
  const global = new RegExp(pattern.source, pattern.flags.includes('g') ? pattern.flags : pattern.flags + 'g');
  for (const m of text.matchAll(global)) {
    if (!isNegatedClaim(text, m.index ?? 0)) return true;
  }
  return false;
}

// Currency-tagged price scan. This sales agent's entire ratified Claim
// Register is EC$-denominated, so any US$ or unqualified $ figure is always
// out of scope for it — block outright rather than allow-listing amounts
// that were never ratified for this agent in the first place.
const PRICE = /(EC\$|US\$|\$)\s?([\d,]+(?:\.\d+)?)/gi;

/**
 * Scans a generated reply for a sales tenant. Non-sales tenants pass through
 * untouched — this filter has zero blast radius outside SALES_TENANT_IDS.
 */
export function guardReply(text: string, tenantId: string): GuardResult {
  if (!SALES_TENANT_IDS.has(tenantId)) return { text, blocked: false };

  for (const { id, pattern, requiresPositiveClaim } of HARD_NEVERS) {
    const hit = requiresPositiveClaim ? hasPositiveClaim(text, pattern) : pattern.test(text);
    if (hit) return { text: DEFLECTION, blocked: true, rule: id };
  }

  for (const m of text.matchAll(PRICE)) {
    const currency = m[1].toUpperCase();
    const amount = Number(m[2].replace(/,/g, ''));
    if (currency !== 'EC$') {
      return { text: DEFLECTION, blocked: true, rule: 'non_ec_price' };
    }
    if (!RATIFIED_EC_AMOUNTS.has(amount) && amount !== RATIFIED_PER_MIN_RATE) {
      return { text: DEFLECTION, blocked: true, rule: 'unratified_price' };
    }
  }

  return { text, blocked: false };
}
