/**
 * Claim-guard — output filter enforcing the approved Claim Register + hard-never
 * list for the EMA/Isola sales-concierge agents ("Iris" in the Lane 1 dispatch).
 *
 * Why this is a post-generation filter, not a prompt edit: these agents run on
 * brain_provider='clawith', where the reply text is generated by an external
 * system (Clawith/Paperclip) that this repo has no credentials for and does not
 * control — tryIsolaBridge()/tryClawithLegacy() in brain-provider.ts never
 * forward the `system` prompt to it. This is the only reachable enforcement
 * point for any provider's output, called from generateReply()'s single
 * chokepoint in lib/brain-provider.ts.
 *
 * Scope: enforcement (block + deflect) applies ONLY to SALES_TENANT_IDS below.
 * A platform-wide audit-only detector for all clawith tenants is an explicit
 * future follow-on — applying this tenant's price allow-list to other tenants
 * would incorrectly block their own real prices.
 */

export const SALES_TENANT_IDS: ReadonlySet<string> = new Set([
  'ema_sales_tenant',
  '43b006e4-33e0-42a8-bec7-4422ba290d79',
]);

// Ratified once-off/setup + monthly figures (EC$) from the approved Claim
// Register. No other EC$ figure may appear in a sales-tenant reply.
const RATIFIED_EC_AMOUNTS = new Set([750, 249, 250, 99, 149]);
// Ratified per-minute voice rate — sourced from the same env var Magnus/Lite
// billing already uses, so this can't drift from the live billing rate.
const RATIFIED_PER_MIN_RATE = Number(process.env.LITE_DOMINICA_RATE_EC_PER_MIN ?? '0.27');

export interface GuardResult {
  text: string;
  blocked: boolean;
  /** Rule id, for audit logging only — never included in the customer-facing text. */
  rule?: string;
}

// Exported so brain-provider.ts can reuse the exact same claim-safe text on
// the fail-closed guard-error path — one source of truth for what the
// customer sees when the guard can't vouch for the raw reply, whether that's
// a rule hit or an unexpected error evaluating the rules.
export const DEFLECTION =
  "I don't have a confirmed answer for that — let me get you accurate details from our team. I'll flag this conversation for a person to follow up.";

// Hard-never deny-list — heuristic regexes, first pass. Expect tuning as the
// regression suite and live traffic surface false positives/negatives.
const HARD_NEVERS: { id: string; pattern: RegExp }[] = [
  { id: 'voice_ai', pattern: /\bvoice[\s-]?AI\b|\bAI\s+(answers?|picks?\s+up|handles?)\s+(your\s+|the\s+)?(phone\s*)?calls?\b/i },
  { id: 'unlimited_autonomy', pattern: /\bunlimited autonomy\b|\bfully autonomous\b|\bno human (oversight|involvement|needed)\b/i },
  { id: 'guaranteed_accuracy', pattern: /\bguarantee[sd]?\b[^.?!]{0,40}\b(sales|accuracy|results|conversion)s?\b/i },
  { id: 'missed_call_recovery', pattern: /\bmissed[\s-]call recovery\b|\brecovers?\s+(every|all)\s+missed calls?\b/i },
  { id: 'complex_ivr', pattern: /\bIVR\b|\bmulti-?level (phone )?menu\b/i },
  { id: 'instant_self_service', pattern: /\binstant self-?service\b|\b14-?day free\b|\bself-?serve sign-?up\b/i },
  { id: 'automated_refunds', pattern: /\bautomat(ed|ic) refunds?\b/i },
  { id: 'every_intl_route', pattern: /\bevery international (route|destination)\b|\ball countries\b/i },
  { id: 'autonomous_finance', pattern: /\bautonomous(ly)?\s+(move|transfer|charge)s?\b|\bAI\s+(can|will)\s+(move|transfer)\s+money\b/i },
  // Order-independent: catches both "guaranteed migration of every WhatsApp
  // number" and "we migrate every WhatsApp number, guaranteed."
  { id: 'guaranteed_migration', pattern: /(?=[\s\S]*\bguarantee[sd]?\b)(?=[\s\S]*\bmigrat(e|ion|ing)\b)(?=[\s\S]*\b(every|all)\s+(your\s+)?WhatsApp numbers?\b)/i },
];

const EC_PRICE = /EC\$\s?([\d,]+(?:\.\d+)?)/gi;

/**
 * Scans a generated reply for a sales tenant. Non-sales tenants pass through
 * untouched — this filter has zero blast radius outside SALES_TENANT_IDS.
 */
export function guardReply(text: string, tenantId: string): GuardResult {
  if (!SALES_TENANT_IDS.has(tenantId)) return { text, blocked: false };

  for (const { id, pattern } of HARD_NEVERS) {
    if (pattern.test(text)) return { text: DEFLECTION, blocked: true, rule: id };
  }

  for (const m of text.matchAll(EC_PRICE)) {
    const amount = Number(m[1].replace(/,/g, ''));
    if (!RATIFIED_EC_AMOUNTS.has(amount) && amount !== RATIFIED_PER_MIN_RATE) {
      return { text: DEFLECTION, blocked: true, rule: 'unratified_price' };
    }
  }

  return { text, blocked: false };
}
